const A = '#contact';
const link = (label, href = A) => `<a class="text-link" href="${href}">${label} <span>↗</span></a>`;
const cards = (items, className = 'grid') => `<div class="${className}">${items.map(([title, text, cta]) => `<article class="card"><h3>${title}</h3><p>${text}</p>${cta ? link(cta) : ''}</article>`).join('')}</div>`;
const features = (items) => `<div class="feature-list">${items.map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`;
const steps = (items) => `<div class="numbered">${items.map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`;
const section = (title, intro, body, kicker = '') => `<section class="content-block">${kicker?`<p class="kicker">${kicker}</p>`:''}<h2>${title}</h2>${intro?`<p class="section-intro">${intro}</p>`:''}${body}</section>`;

const techServices = [
 ['Web Application Development','Progressive web apps, customer portals, dashboards, marketplaces and internal tools — built on React and Next.js with server-side rendering, so they load fast and rank well.','Get a quote'],
 ['Mobile App Development','Native iOS and Android, or cross-platform with React Native and Flutter. Push notifications, offline mode, in-app payments, biometric auth and deep linking.','Get a quote'],
 ['Custom Software & SaaS Platforms','For businesses whose process genuinely doesn’t fit an existing product. Multi-tenant architecture, role-based access, subscription billing and usage metering.','Get a quote'],
 ['MVP & Startup Development','For founders who need something real in front of users before the next funding conversation. We scope ruthlessly and ship a working product.','Get a quote'],
 ['UI/UX Design','Research, user flows, wireframes, interactive prototypes and a complete design system. We test the experience before it’s built.','Get a quote'],
 ['Cloud & DevOps','Deployment, scaling and the unglamorous infrastructure work that determines whether your product survives its first busy week.','Get a quote'],
 ['API Development & Integration','Connecting the systems you already run — payment gateways, logistics providers, accounting software, marketplaces and government portals.','Get a quote'],
 ['Maintenance & Support','Ongoing monitoring, security patching, dependency updates, performance tuning and feature development on retainer.','Get a quote']
];
const aiServices = [
 ['LLM Integration','Embedding large language models into your existing software — GPT, Claude, Gemini or open-source models. Summarisation, drafting, classification and extraction.','Discuss this'],
 ['AI Agents & Assistants','Assistants that do things, not just answer things. Built with guardrails, approval steps and full audit logs.','Discuss this'],
 ['Document Intelligence','Automated extraction from invoices, purchase orders, contracts, forms and scanned paperwork, with exception flagging.','Discuss this'],
 ['Semantic & AI Search','Search that understands intent instead of matching keywords, using vector embeddings and retrieval grounded in your own data.','Discuss this'],
 ['Workflow Automation','Connecting your tools so processes run without a person in the middle — approvals, invoicing, inventory alerts and lead routing.','Discuss this'],
 ['Predictive Analytics & ML','Custom machine learning on your historical data: demand forecasting, churn prediction, dynamic pricing and anomaly detection.','Discuss this'],
 ['Generative Media & Content AI','Image, copy and video generation pipelines built into your marketing and product workflows.','Discuss this'],
 ['AI Consulting & Readiness','A structured assessment of where AI will and won’t pay off in your business, with a prioritised roadmap.','Discuss this']
];
const erpModules = [
 ['Inventory & Warehouse Management','Real-time stock across locations, barcode and QR scanning, batch tracking and reorder automation.'],['Finance & Accounting','Invoicing, payables and receivables, general ledger, multi-currency, tax compliance and bank reconciliation.'],['Sales & Order Management','Quotations, order processing, pricing rules, delivery scheduling and returns.'],['Procurement & Vendor Management','Purchase requisitions, vendor comparison, PO generation and three-way matching.'],['Manufacturing & Production','Bill of materials, production planning, work orders, shop-floor tracking and quality control.'],['HR & Payroll','Employee records, attendance, leave management, payroll processing and statutory compliance.'],['CRM & Lead Management','Lead capture, pipeline stages, automated follow-ups and sales performance dashboards.'],['Project & Resource Management','Project planning, task allocation, timesheets, budget tracking and billable-hour reporting.'],['Reporting & Business Intelligence','Role-based dashboards, custom report builder, scheduled email reports and drill-down analytics.'],['Asset & Maintenance Management','Asset register, depreciation, preventive maintenance schedules and downtime tracking.']
];
const marketingServices = [
 ['Content Strategy & Copywriting','Messaging frameworks, content calendars, website copy, blogs, newsletters, case studies and sales collateral.','Discuss this'],['Social Media Management','End-to-end management across Instagram, LinkedIn, YouTube, Facebook and X. Strategy, creative, scheduling and reporting.','Discuss this'],['Video & Photo Production','Full production: concept, script, storyboard, shoot, edit, colour and sound.','Discuss this'],['Performance Marketing','Paid campaigns on Google, Meta, LinkedIn and YouTube, run against pipeline and revenue.','Discuss this'],['SEO & Organic Growth','Technical SEO, on-page optimisation, content clusters, link building and local SEO.','Discuss this'],['Branding & Identity','Logo, visual identity, typography, colour systems, brand guidelines, packaging and collateral.','Discuss this'],['Influencer & Creator Marketing','Creator identification, outreach, negotiation, brief-writing and performance tracking.','Discuss this'],['Marketing Automation & CRM','Email and WhatsApp flows, lead scoring, nurture sequences and CRM setup.','Discuss this']
];

const pages = [
 { id:'home', kicker:'Development + Marketing, under one roof', title:'We build the technology that runs your business — and the marketing that grows it.', lead:'Most companies hire one agency to build the product and another to sell it, then spend months translating between them. We do both. Our technology wing ships web apps, mobile apps, ERPs and AI automation. Our marketing wing handles content, production and media. Same team, same brief, one point of accountability.', actions:[['Book a free consultation',A],['Talk to us',A]], body:()=>[
  section('One company. Two wings. Zero handoff gaps.','Technology and marketing fail separately far more often than they fail together. A beautiful product nobody hears about. A brilliant campaign pointing at software that breaks. We run both wings in the same building, on the same timeline, reporting to the same project lead.', `<div class="two-col"><div><h3>Technology Wing</h3><p>Custom web and mobile applications, SaaS platforms, ERP and CRM systems, AI integration and workflow automation. We architect, build, deploy and maintain — full lifecycle, no subcontracting.</p>${link('Explore technology','#technology')}</div><div><h3>Marketing Wing</h3><p>Content strategy, copywriting, video and photo production, social media management, performance campaigns and brand identity. The creative side that turns a working product into a growing one.</p>${link('Explore marketing','#marketing')}</div></div>`),
  section('Everything you need, built in-house','From a first MVP to a full enterprise rollout, these are the capabilities we bring to every engagement.', cards([['Web Application Development','Fast, secure, scalable web apps built on React and Next.js — from customer portals to full SaaS platforms.','Learn more'],['Mobile App Development','Native and cross-platform iOS and Android apps, designed for real usage patterns.','Learn more'],['Custom Software & SaaS','Purpose-built platforms for businesses whose workflow doesn’t fit off-the-shelf tools.','Learn more'],['ERP Development','Inventory, finance, HR, procurement and production in one system that matches how your business runs.','Learn more'],['CRM Development','Lead capture to closed deal, with pipelines, automations and reporting built around your sales process.','Learn more'],['AI & LLM Integration','Chat assistants, document intelligence, semantic search and generative features embedded into your software.','Learn more'],['Workflow Automation','Connect your tools and remove the manual steps. Invoices, onboarding, reporting and approvals that run themselves.','Learn more'],['Content & Social Media','Strategy, copy, design and daily management across the platforms where your customers spend time.','Learn more'],['Video & Photo Production','Scripting, shooting and editing — product films, founder interviews, ad creative and social-first video.','Learn more']])),
  section('How we work','No black boxes. You’ll know what’s being built, what it costs and when it lands, from week one.',steps([['Discover','We sit with your team, map the current workflow and find where the money and the hours are actually leaking. You get a written scope before anyone writes code.'],['Design','Wireframes, then clickable prototypes, then final UI. You approve the experience before development starts.'],['Build','Two-week sprints with a working demo at the end of each one. A shared board, a named project lead and a weekly call.'],['Launch & Grow','We deploy, monitor and support. Then the marketing wing takes over — content, campaigns and creative that put the thing you just built in front of people.']])),
  section('Why businesses choose Scalable Technologies','',features([['Two capabilities, one invoice','Development and marketing under one contract, one timeline and one project lead.'],['Senior people on your project','The person who scopes your project is the person who builds it.'],['Built to be owned','You get the source code, the repositories, the cloud accounts and the documentation.'],['AI where it earns its place','We use AI to remove real hours from real workflows.'],['Fixed scope, transparent pricing','A written scope, a fixed quote and a clear change-request process.'],['Support after go-live','Monitoring, updates, security patches and a support SLA you can actually hold us to.']])),
  section('Industries we build for','Different sectors, same underlying problem — systems that don’t talk to each other and marketing that doesn’t reflect the product.', '<div class="marquee"><span>Manufacturing · Retail &amp; E-commerce · Healthcare · Education · Logistics &amp; Supply Chain · Real Estate · Professional Services · Hospitality · Fintech · D2C Brands &nbsp;&nbsp;&nbsp;&nbsp; Manufacturing · Retail &amp; E-commerce · Healthcare · Education · Logistics &amp; Supply Chain · Real Estate · Professional Services · Hospitality · Fintech · D2C Brands</span></div>'),
  section('Let’s figure out what you actually need.','A 30-minute call, no pitch deck. Tell us what’s slow, what’s broken or what you’re trying to launch, and we’ll tell you honestly whether we’re the right people to build it — and roughly what it would take.', `<div class="actions"><a class="button" href="#contact">Book a free consultation <i>↗</i></a><a class="button secondary" href="https://wa.me/919766993471">WhatsApp us <i>↗</i></a></div>`)
 ]},
 { id:'about', kicker:'About us', title:'We started Scalable Technologies because good products kept dying of bad marketing.', lead:'And good marketing kept pointing at broken software. Businesses were paying two vendors to solve one problem, and the gap between them was where budgets and timelines went to die. So we built a company that covers both sides — engineers and creatives working from the same brief.', actions:[['Work with us',A]], body:()=>[
 section('Our story','Scalable Technologies was built to close the gap between software and the market that needs it.', `<p class="lead">A single team that can take a business from a working product to a market that knows it exists, without the handoff between a dev shop and a marketing agency that usually gets lost in translation.</p><p class="section-intro">We run two wings. The technology wing builds applications, platforms, ERP systems and AI automation. The marketing wing handles content, production, social media and campaigns. They share a project board, a weekly standup and a single point of accountability to you.</p>`),
 section('Mission & vision','',`<div class="two-col"><div><h3>Our mission</h3><p>To give growing businesses the same quality of technology and marketing that large enterprises take for granted — without the enterprise price tag or the six-month procurement cycle.</p></div><div><h3>Our vision</h3><p>To become the default partner for businesses that want to build and grow at the same time — one team that can take an idea from whiteboard to working software to a market that knows it exists.</p></div></div>`),
 section('The way we work','',features([['Say the hard thing early','If a deadline is unrealistic or a feature isn’t worth building, you’ll hear it in week one, not week twelve.'],['Build it like we’ll maintain it','Clean architecture and real documentation are how we avoid rebuilding the same thing twice.'],['Own the outcome, not the ticket','Our job is to make sure the thing we built actually solved the problem you hired us for.'],['Make it usable before making it clever','We design for the person who has to use it every day.'],['Protect what’s yours','Your code, your data, your accounts and your credentials. Full handover, documented.'],['Improve every sprint','Retrospectives after every cycle, internally and with you.']])),
 section('Want to see if we’re a fit?','The fastest way to find out is a conversation. Tell us about the project and we’ll be straight with you about whether we’re the right team for it.',`<a class="button" href="#contact">Start a conversation <i>↗</i></a>`)
 ]},
 { id:'technology', kicker:'Technology', title:'Software built for how your business actually works.', lead:'Off-the-shelf tools force you to reshape your process around their assumptions. We do the opposite. Whether it’s a customer-facing web app, an internal platform, a mobile product or a SaaS business, we design around your workflow and build it to hold up under real load.', actions:[['Discuss your project',A]], body:()=>[
 section('Development services','',cards(techServices)),
 section('The stack we build on','Chosen for maturity and hiring depth, not novelty.',`<div class="two-col"><div><h3>Frontend</h3><p>React · Next.js · TypeScript · Tailwind CSS · Vue.js</p><h3>Mobile</h3><p>React Native · Flutter · Swift · Kotlin</p><h3>AI &amp; Data</h3><p>OpenAI · Anthropic · LangChain · Pinecone · TensorFlow · PyTorch</p></div><div><h3>Backend</h3><p>Node.js · Python · Django · FastAPI · Express · Laravel</p><h3>Database</h3><p>PostgreSQL · MySQL · MongoDB · Redis · Supabase</p><h3>Cloud &amp; DevOps</h3><p>AWS · Azure · Google Cloud · Docker · Kubernetes · Vercel</p></div></div>`),
 section('Ways to work with us','',cards([['Fixed Scope Project','A defined deliverable, a fixed quote and a fixed timeline. Best when you know what you want built.'],['Dedicated Team','A ring-fenced team of developers, designers and a project lead working only on your product, billed monthly.'],['Retainer & Support','A monthly block of hours for maintenance, improvements and new features on an existing system.']])),
 section('Tell us what you’re building.','Send us the idea, the problem or the half-finished project someone else abandoned. We’ll come back with an honest assessment and a realistic number.',`<a class="button" href="#contact">Request a proposal <i>↗</i></a>`)
 ]},
 { id:'ai-automation', kicker:'AI & Automation', title:'AI that removes work, not AI that adds a chatbot.', lead:'Most AI projects fail because they start with the technology and look for a problem afterwards. We start with your workflow — the approvals that sit in someone’s inbox for three days, the reports assembled by hand every Monday, the invoices keyed in twice. Then we build the smallest system that makes that work disappear.', actions:[['Book an AI assessment',A]], body:()=>[
 section('Where the hours are going','',cards([['Data entered more than once','The same order details typed into a form, a spreadsheet and an accounting system, by three different people.'],['Documents read by humans','Invoices, purchase orders, contracts, CVs and claims opened, skimmed and manually summarised — thousands of times a year.'],['Reports assembled by hand','Someone exporting four dashboards every Monday morning and pasting them into a deck that’s out of date by Tuesday.'],['Questions answered repeatedly','Support and internal teams answering the same forty questions forever, because the answers live in a PDF nobody can find.']])),
 section('AI services','',cards(aiServices)),
 section('Our approach','',steps([['Audit the workflow','We map the process end to end and count the hours. If there aren’t enough hours in it to justify the build, we say so.'],['Pilot one use case','One high-value workflow, built end to end with defined success criteria.'],['Integrate, don’t bolt on','The system goes inside your existing tools. Anything that requires a separate tab gets abandoned within a month.'],['Measure and expand','We track time saved, error rates and throughput against the baseline.']])),
 section('Find out what AI could actually save you.','We’ll map two or three of your workflows, estimate the hours a system could remove and tell you which — if any — are worth building.',`<a class="button" href="#contact">Book an AI assessment <i>↗</i></a>`)
 ]},
 { id:'erp', kicker:'ERP & CRM', title:'One system that runs the business. Not nine that argue with each other.', lead:'Most growing companies end up with inventory in one tool, accounts in another, HR in a spreadsheet and the real numbers in someone’s head. A custom ERP puts all of it in one place, matched to how your business already operates.', actions:[['Book an ERP demo',A]], body:()=>[
 section('The problem','',features([['Data lives in five places','Nobody can prove which number is right.'],['Month-end takes a week','Exporting, reconciling and re-keying by hand.'],['Stock is a guess','Physical and system inventory diverged months ago.'],['Reporting is retrospective','Decisions get made before the report is ready.'],['Off-the-shelf doesn’t fit','You’re paying for modules your team never opens.'],['Nothing is traceable','When something goes wrong, no one can see why.']])),
 section('Modules we build','',cards(erpModules)),
 section('ERP services','',cards([['Custom ERP Development','A system built from scratch around your processes and reporting needs.'],['ERP Implementation','Configuring and deploying an existing platform, with custom modules where needed.'],['Legacy ERP Migration','Moving off an ageing system without losing history or stopping operations.'],['ERP Integration','Connecting your ERP to e-commerce, logistics, payment gateways and tax portals.'],['Mobile ERP Access','Companion apps for field staff and management — approvals, stock checks and dashboards.'],['ERP Support & Enhancement','Ongoing maintenance, training and new module development.']])),
 section('Implementation process','',steps([['Process mapping','We document how work actually happens, including the workarounds nobody mentions in meetings.'],['Blueprint & approval','A written functional specification. You sign off before development begins.'],['Development & configuration','Built in phases, with a working demo of each module.'],['Data migration','Cleaning, mapping and importing your existing records, with validation reports.'],['Training & parallel run','Role-based training, then old and new systems run side by side until the numbers match.'],['Go-live & support','Cutover with close support, then ongoing maintenance.']])),
 section('Custom ERP vs. off-the-shelf','',`<table class="comparison"><thead><tr><th></th><th>Off-the-shelf</th><th>Custom ERP</th></tr></thead><tbody><tr><td>Fit to your process</td><td>You adapt to the software</td><td>The software matches how you work</td></tr><tr><td>Licensing cost</td><td>Per user, per month, forever</td><td>One-time build, you own it</td></tr><tr><td>Customisation</td><td>Limited, or expensive add-ons</td><td>Anything, on request</td></tr><tr><td>Data ownership</td><td>On vendor servers</td><td>Your servers or your cloud</td></tr><tr><td>Support</td><td>Ticket queue</td><td>A named team who built it</td></tr></tbody></table>`),
 section('See what a system built for you looks like.','Book a walkthrough and we’ll show you working modules, then talk through what your version would involve — modules, timeline and budget range.',`<a class="button" href="#contact">Book an ERP demo <i>↗</i></a>`)
 ]},
 { id:'marketing', kicker:'Marketing', title:'The best product in the category still loses to the one people have heard of.', lead:'Our marketing wing handles the other half of the job — the content, the creative, the shoots and the campaigns that put your business in front of the people who should be buying from it.', actions:[['Get a marketing proposal',A]], body:()=>[
 section('Marketing services','',cards(marketingServices)),
 section('Our production setup','We shoot in-house, which means faster turnarounds, tighter budgets and no coordination tax between three vendors.',cards([['In-house studio','Controlled lighting for product, portrait and interview work.'],['On-location crew','Factories, offices, retail floors, events and outdoor shoots.'],['Post-production','Editing, motion graphics, animation, colour grading, sound design and subtitling.'],['Volume content','Batch shooting built for social — a month of short-form content in a single day.']])),
 section('Let’s build the audience your product deserves.','Tell us where you are — no presence, inconsistent presence, or plenty of activity and not enough results — and we’ll propose the shortest route to fixing it.',`<a class="button" href="#contact">Get a marketing proposal <i>↗</i></a>`)
 ]},
 { id:'contact', kicker:'Contact', title:'Tell us what you’re trying to solve.', lead:'No sales script and no pitch deck. Fill in the form or call us directly, and you’ll talk to someone who can actually assess the project.', body:()=>[
 section('Start a conversation','',`<div class="contact-layout"><form id="contact-form" action="#" onsubmit="event.preventDefault(); this.querySelector('button').textContent='Thank you — we’ll be in touch';"><div class="form-row"><label>Full name<input required name="name" type="text" autocomplete="name" /></label><label>Work email<input required name="email" type="email" autocomplete="email" /></label></div><div class="form-row"><label>Phone / WhatsApp<input required name="phone" type="tel" autocomplete="tel" /></label><label>Company name<input name="company" type="text" autocomplete="organization" /></label></div><label>What do you need help with?<select required name="service"><option value="">Choose a service</option><option>Web Development</option><option>Mobile App</option><option>Custom Software / SaaS</option><option>ERP</option><option>CRM</option><option>AI & Automation</option><option>UI/UX Design</option><option>Content & Social Media</option><option>Video Production</option><option>Performance Marketing</option><option>SEO</option><option>Branding</option><option>Not sure yet</option></select></label><div class="form-row"><label>Budget range<select name="budget"><option>Not sure yet</option><option>Under ₹1 lakh</option><option>₹1–5 lakh</option><option>₹5–10 lakh</option><option>₹10 lakh+</option></select></label><label>Timeline<select required name="timeline"><option>Immediately</option><option>Within 1 month</option><option>1–3 months</option><option>3–6 months</option><option>Just exploring</option></select></label></div><label>Tell us about the project<textarea required name="message" placeholder="What’s the problem you’re trying to solve? What have you tried so far?"></textarea></label><button class="button" type="submit">Send enquiry <i>↗</i></button><p class="form-note">We reply to every enquiry — including the ones we’re not the right fit for.</p></form><aside class="contact-details"><article><h3>Email</h3><p><a href="mailto:scalabletechnologies11@gmail.com">scalabletechnologies11@gmail.com</a></p></article><article><h3>Phone &amp; WhatsApp</h3><p><a href="tel:+919766993471">+91 9766993471</a><br />Monday to Saturday</p></article><article><h3>Office</h3><p>MHADA Towers, Nanekar Park,<br />Waghere, Pimpri 411018</p></article></aside></div>`),
 section('Frequently asked questions','',`<div class="faq"><details><summary>How much will my project cost?</summary><p>It depends on scope. We give a fixed written quote after the first scoping call.</p></details><details><summary>How long does a project take?</summary><p>Timing depends on the scope, the modules and any migration work. We’ll provide a realistic delivery plan during scoping.</p></details><details><summary>Do I own the code?</summary><p>Yes, completely. Source code, repositories, cloud accounts, credentials and documentation are handed over on project completion.</p></details><details><summary>Can I hire just one wing?</summary><p>Yes. You can engage us for development or marketing on its own; the combined engagement is never a condition.</p></details><details><summary>What happens after launch?</summary><p>We provide post-launch support and can continue with a monthly retainer for monitoring, updates and new features.</p></details><details><summary>Will I get the same team throughout?</summary><p>Yes. The person who scopes your project stays on it through delivery.</p></details></div>`),
 section('One last thing.','If you’re not sure what you need yet, that’s a perfectly good reason to get in touch. A lot of our best projects started as a conversation about a problem nobody had defined yet.',`<a class="button" href="#contact-form">Send us a message <i>↗</i></a>`)
 ]}
];

const main = document.querySelector('#site-content');
main.innerHTML = pages.map(page => `<section class="page" id="${page.id}"><p class="kicker">${page.kicker}</p><h1>${page.title}</h1><p class="lead">${page.lead}</p>${page.actions ? `<div class="actions">${page.actions.map(([label,href],i)=>`<a class="button ${i?'secondary':''}" href="${href}">${label} <i>↗</i></a>`).join('')}</div>` : ''}${page.body().join('')}</section>`).join('');

document.querySelector('#footer').innerHTML = `<div class="footer-grid"><div><a class="brand" href="#home">SCALABLE<span>TECHNOLOGIES</span></a><p>We build the software that runs your business and the marketing that grows it. One team, two wings, end-to-end accountability.</p></div><div><h3>Technology</h3><a href="#technology">Web applications</a><a href="#technology">Mobile apps</a><a href="#technology">Custom software &amp; SaaS</a><a href="#technology">UI/UX design</a><a href="#technology">Cloud &amp; DevOps</a></div><div><h3>AI, ERP &amp; Marketing</h3><a href="#ai-automation">AI &amp; LLM integration</a><a href="#ai-automation">Workflow automation</a><a href="#erp">ERP development</a><a href="#erp">CRM development</a><a href="#marketing">Content &amp; social media</a><a href="#marketing">Production &amp; shoots</a></div><div><h3>Get in touch</h3><a href="mailto:scalabletechnologies11@gmail.com">scalabletechnologies11@gmail.com</a><a href="tel:+919766993471">+91 9766993471</a><p>MHADA Towers, Nanekar Park,<br>Waghere, Pimpri 411018</p></div></div><p class="copyright">© 2026 Scalable Technologies. All rights reserved.</p>`;

const toggle = document.querySelector('.menu-toggle');
const nav = document.querySelector('#site-nav');
toggle.addEventListener('click', () => { const open = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded',open); toggle.textContent = open ? 'Close' : 'Menu'; });
nav.addEventListener('click', () => { nav.classList.remove('open'); toggle.setAttribute('aria-expanded','false'); toggle.textContent='Menu'; });

// The film is deliberately paused. Scrolling is the only thing that advances it.
const video = document.querySelector('#scroll-video');
let duration = 0;
let requested = false;
let lastRequestedTime = -1;

function prepareScrollVideo() {
  if (Number.isFinite(video.duration) && video.duration > 0) duration = video.duration;
  video.pause();
  syncVideo();
}

function syncVideo() {
  requested = false;
  if (!duration) return;
  const scrollableHeight = Math.max(1, document.documentElement.scrollHeight - window.innerHeight);
  const progress = Math.min(1, Math.max(0, window.scrollY / scrollableHeight));
  const targetTime = Math.min(duration - 0.05, progress * duration);
  // Do not queue a new decoder seek while the last one is in progress.
  // The local file is encoded with a keyframe every half-second for fast seeking.
  if (!video.seeking && Math.abs(lastRequestedTime - targetTime) > 0.045) {
    video.currentTime = targetTime;
    lastRequestedTime = targetTime;
  }
}

video.addEventListener('loadedmetadata', prepareScrollVideo);
video.addEventListener('durationchange', prepareScrollVideo);
video.addEventListener('canplay', () => video.pause());
video.addEventListener('play', () => video.pause());
if (video.readyState >= 1) prepareScrollVideo();
window.addEventListener('scroll', () => {
  if (!requested) { requested = true; requestAnimationFrame(syncVideo); }
}, { passive: true });
window.addEventListener('resize', syncVideo);
document.addEventListener('visibilitychange', () => video.pause());
